# Configuration
CLUSTER_SIZE=4
SSH_PRIVATE_KEY="#{ENV['HOME']}/.ssh/id_rsa"
SSH_PUBLIC_KEY="#{ENV['HOME']}/.ssh/id_rsa.pub"

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.box_version = "20171212.0.0"

    config.ssh.insert_key = false
    config.ssh.private_key_path = [SSH_PRIVATE_KEY, "~/.vagrant.d/insecure_private_key"]
    config.vm.provision "file", source: SSH_PUBLIC_KEY, destination: "~/.ssh/authorized_keys"

    (1..CLUSTER_SIZE).each do |i|
        config.vm.define "node#{i}" do |node|
            node.vm.hostname = "node#{i}"

            node.vm.network "private_network", ip: "10.240.0.2#{i}"

            node.vm.provision "shell",
                inline: "echo '10.240.0.21 node1
10.240.0.22 node2
10.240.0.23 node3
10.240.0.24 node4' >> /etc/hosts"
        end
    end
end
